### PR TITLE
Revised page

### PR DESCRIPTION
**Pull request by NiiazalyDzhumaliev**
Embedding Images and Video

### CODE REVIEW

**Comment by NiiazalyDzhumaliev** [comment]
We accidentally merge the project, now we have new pull request

**Comment by DickensJuma** [comment]
we have corrected the issues you addressed, included the CSS. We are sorry we merged the branch earlier, won't do it again.

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟
Great work on this project, but we need to fix the issues below before moving on ⬇️

- [x] Please fix the Validators errors.

Screenshot from 2020-02-21 08-22-59

- [x] Consider matches the appearance of the youtube video player page. 
They should be "appropriately sized and positioned" (as described in Odin project description). 





- [x] Consider aligned the 'search bar' to the middle of the navbar.

- [x] 'Recommendation videos' please align them at the right side (match the appearance of the original page).

- [x] Consider be more specific with your comments on your commits, for example: 'delete spaces' or revise CSS' etc.. Explain why you did that in a few words, please be more descriptive.

[OPTIONAL]

- [x] You have repeated v-1...v-5 images twice, please delete one copy of them. (look that you have the same images on the 'images' file.

- [x] I encourage you the use the `<nav>` tag for the major navigation links, of the `<main>` tag for the dominant content of the `<body>` of a document and the `<footer>` tag for the footer.

Good job using the Microverse readme template! 

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by NiiazalyDzhumaliev** [comment]
We revised our project accoriding to your review. Please check it.

**Comment by lekegitrepo** [comment]
This PR is under **Review by: [TSE] Temitayo Adeleke**

**Comment by SofiBretz** [comment]
### Well done Team 👏

[OPTIONAL]

- [x] Your screenshot is not displaying on the readme file.

- [x] Please add a demo link in your readme file.

- [x] You are still missing the comment section. You can include only one or two mock comments to display it.

- [x] You could use the same icons on the original page navbar to make your project look better. ✨.

Project Approved!
**You can merge 👍**
SofiBretz.

**Pull request merged**
